### ISSUE TITLE
Conflicting with GSAP's CSSPlugin

### ISSUE THREAD

**Issue by virajsoni06** [BrentonCozby/dom-slider#1]
Hey @BrentonCozby, when I load this plugin alongside with CSSPlugin from GSAP it throws a `'classList' of undefined` error.

**Comment by BrentonCozby** [comment]
Hey @virajsoni06 , thanks for the comment. I'll look into it this week.

**Comment by BrentonCozby** [comment]
@virajsoni06 I'm not familiar with GSAP, but I've included the CDN in a script tag and the error comes from "TweenLite" (GSAP), not dom-slider, so I am unable to figure out what is causing the error.

Please give me more information about the error you see.

**Comment by virajsoni06** [comment]
Hey @BrentonCozby, yeah the error is coming from TweenLite. More specifically it happens when `clearProps` property is used. 

I spent some time looking into `dom-slider`'s code and haven't able to figure out exactly whats wrong. But it's likely that it is related to `Object.prototype.slideDown` function

Will give it a go again sometime next week and see if I can figure out the issue

**Comment by BrentonCozby** [comment]
Hey, I refactored dom-slider to be an independent module. Its methods are no longer built on the Object prototype chain. These are breaking changes (different API).
