### ISSUE TITLE
Cannot redefine property: slideDown

### ISSUE THREAD

**Issue by jonaswebdev** [BrentonCozby/dom-slider#8]
Hi, I created a little script which uses "dom-slider" and working well "alone", but when I put on production website where there are many other scripts, including jQuery, I got this error:
`Cannot redefine property: slideDown`.

I research quickly and saw something related with "slideDown" (re)declaration ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_redefine_property)).

I don't know it's a problem on my side, and there is a way to avoid this conflict, like the "dom-slider" method should work only my application scope. 
Or if you could fix it following the idea on define `configurable: true` but we need to think on the "side-effects" from this change.

Let me know you think about this, please.

Thanks in advance

PS: there is a [question](https://stackoverflow.com/questions/25517989/why-cant-i-redefine-a-property-in-a-javascript-object) and some comments, maybe could help us :)

**Comment by julkue** [comment]
Suggestion: Avoid manipulating DOM properties and methods and make it an exportable module with methods to call. Then we can create an instance and call slide methods, instead of calling DOM methods which causes these conflicts.

**Comment by BrentonCozby** [comment]
Hey, I've made that update. Sort of...it's not exportable, but the methods are no longer on the DOM prototypes. These are breaking changes so I've bumped the version from 1.x.x to 2.0.0.
